name: Build Frontend 

on:
  workflow_call:
    secrets:
    GITHUB_TOKEN:
      required: true
    SONAR_TOKEN:
      required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'
          cache: 'npm'

      - name: Update NPM
        run: npm install -g npm@8
        
      - name: Install dependencies
        run: npm ci

      - name: Run Linters
        run: npm run lint

      - name: Build React site
        run: |
          rm -rf ./dist 
          npm run build
  sonarcloud:
    name: SonarCloud
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}