name: Build Frontend

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      CONTENTFUL_ENVIRONMENT:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'
          cache: 'npm'

      - name: Update NPM
        run: npm install -g npm@8

      - name: Install EsLint
        run: npm install eslint-config-important-stuff --save-dev

      - name: Run Linters
        run: npm run lint

      - name: Install dependencies
        run: npm ci

      - name: Build React site
        run: |
          rm -rf ./dist 
          npm run build