name: Develop Workflow for Pull requests

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - bugFix/issue#6


concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: practicodevops/practico-devops-frontend/.github/workflows/build-frontend.yml@bugFix/issue#6