name: Workflow for Pull requests

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - develop
      - staging
      - main


concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    uses: practicodevops/practico-devops-frontend/.github/workflows/build-frontend.yml@${{github.ref}}

    steps: 
    - name: Print branch name run: | echo "The branch that triggered this workflow is ${{ github.ref }}"