name: Workflow for Pull requests

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - develop
      - staging
      - main


concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    env:
      base_branch: github.base_ref
    steps:
      - name: develop condition
        if: base_branch == 'develop'
        uses: practicodevops/practico-devops-frontend/.github/workflows/build-frontend.yml@develop
   
      - name: staging condition
        if: base_branch == 'staging'
        uses: practicodevops/practico-devops-frontend/.github/workflows/build-frontend.yml@staging

      - name: main condition
        if: base_branch == 'main'
        uses: practicodevops/practico-devops-frontend/.github/workflows/build-frontend.yml@main
