name: Develop Workflow for Pull requests

on:
  pull_request:
    types: [opened, reopened, edited]

concurrency:
  group: enviroment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: practicodevops/practico-devops-frontend/.github/workflows/pull-request/build-frontend.yml
